import Head from "next/head";
import { Fragment } from "react";
import GetPokemon from "../lib/Pokemon";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Pokedex App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GetPokemon />
    </Fragment>
  );
}
